config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'articles#index'
  resources 'articles'
  resources 'users', only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @articles = Article.order('created_at DESC').includes(:user).page(params[:page]).per(5)
  end

  def new
    @article = Article.new
  end

  def create
    Article.create(create_params)
    redirect_to root_path
  end

  def show
    @article = Article.find(params[:id])
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy if article.user_id == current_user.id
    redirect_to root_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(create_params) if @article.user_id == current_user.id
    redirect_to root_path
  end

  private
  def create_params
    params.require(:article).permit(:title, :detail, :image).merge(user_id: current_user.id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    articles = Article.all
    @articles = user.articles.order('created_at DESC').includes(:user).page(params[:page]).per(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
  <!--Import jQuery before materialize.js-->
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  <script type="text/javascript">
    $('#textarea1').val();
    $('#textarea1').trigger('autoresize');
  </script>


    <%= form_for @article do |f|  %>
      <div class="input-field">
        <%= f.text_field :title, placeholder: "title" %>
      </div>
      <div class="input-field">
        <%= f.text_area :detail, placeholder: "textarea", id: "textarea1", class: "materialize-textarea"  %>
      </div>
      <div>
        <%= f.file_field :image %>
      </div>
      <div id="send1">
        <%= f.submit "Send", class: "btn" %>
      </div>
    <% end %>

app/views/articles/_main.html.erb
      <div class="row">
        <div class="col s3">
        </div>
        <div class="col s6">
          <% @articles.each do |article| %>
          <div class="card">
            <div class="card-image">
              <%= image_tag article.image %>
              <span class="card-title"><%= article.title %></span>
              <span class="card-title2"><%= article.user.nickname %></span>
            </div>
            <div class="card-content">
              <p><%= simple_format(article.detail) %></p>
            </div>
            <div class="card-action">
              <%= link_to "more", article_path(article) %>
              <%= link_to "edit", edit_article_path(article) %>
              <%= link_to "delete", article_path(article), method: :delete %>
            </div>
          </div>
          <% end %>
        </div>
        <div class="col s3">
          <div class="fixed-action-btn">
            <a class="btn-floating btn-large waves-effect waves-light blue right" href="/articles/new">
              <i class="material-icons">mode_edit</i>
            </a>
          </div>
        </div>
      </div>
      <%= paginate @articles %>

app/views/articles/edit.html.erb
<div class="row">
  <div class="col s6 offset-s3">
    <h4>編集</h4>
  </div>
  <div class="col s6 offset-s3">
    <%= render "form" %>
  </div>
</div>

app/views/articles/index.html.erb
<%= render "main"%>

app/views/articles/new.html.erb
<div class="row">
  <div class="col s6 offset-s3">
    <h4>新規作成</h4>
  </div>
  <div class="col s6 offset-s3">
    <%= render "form" %>
  </div>
</div>

app/views/articles/show.html.erb
    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function(){
        $('.parallax').parallax();
      });
    </script>

  <div class="parallax-container">
    <div class="parallax"><img class="responsive-img" alt="parallax" src="<%= @article.image %>"></div>
  </div>
  <div class="section white">
    <div class="row container">
      <h2 class="header"><%= @article.title %></h2>
      <h4 class="header2 right"><%= @article.user.nickname %></h4>
      <p class="grey-text text-darken-3 lighten-3"><%= simple_format(@article.detail) %></p>
    </div>
  </div>
  <div class="parallax-container">
    <div class="parallax"><img class="responsive-img" alt="parallax" src="<%= @article.image %>"></div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Devlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link rel="stylesheet" href="lib/assets/stylesheetss">

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  </head>

  <body data-turbolinks="false">
    <nav class="light-blue accent-">
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">Devlog</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <% if user_signed_in? %>
          <li><%= link_to "SignOut", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "MyPage", user_path(current_user) %></li>
          <li><%= link_to "New", new_article_path %></li>
          <% else %>
          <li><%= link_to "SignIn", new_user_session_path %></li>
          <li><%= link_to "SignUp", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
        <footer class="page-footer light-blue accent-">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Thank you for reading!</h5>
                <p class="grey-text text-lighten-4">Have a nice day!</p>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2019 Copyright H.Katsuyama
            </div>
          </div>
        </footer>
  </body>
</html>

app/views/users/show.html.erb
<%= render "articles/main" %>